server:
  port: 8080

spring:
  datasource:
    # Local development configuration
    #url: ${DB_URL:jdbc:postgresql://127.0.0.1:8081/mediconnect?options=-c%20TimeZone=America/Bogota}
    #username: ${DATABASE_USERNAME_P:postgres}
    #password: ${DB_PASSWORD_P:BkiIzqDwaYxQyVgGUOBSAxTihiBefvUV}

    # Railway remote configuration
    url: jdbc:postgresql://altaria.proxy.rlwy.net:32649/railway
    username: postgres
    password: BkiIzqDwaYxQyVgGUOBSAxTihiBefvUV
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Bogota
  flyway:
    locations: classpath:migration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Security
jwt:
  secret: ${JWT_SECRET:change_this_to_a_strong_secret}
  expiration_minutes: ${JWT_EXP_MINUTES:180}

# Initial admin setup bootstrap (DataInitializer)
admin:
  setup:
    password: ${ADMIN_SETUP_PASSWORD:admin123}

# n8n local integration
n8n:
  api:
    key: ${N8N_API_KEY:dev-secret-key-123}
  webhook:
    url: ${N8N_WEBHOOK_URL:http://localhost:5678/webhook/confirmacion-cita}
    reminder-url: ${N8N_WEBHOOK_REMINDER_URL:http://localhost:5678/webhook/recordatorio-cita}