server:
  port: 8080

spring:
  datasource:
    #Local development configuration
    url: ${DB_URL_MC}
    username: ${DATABASE_USERNAME_P}
    password: ${DATABASE_PASSWORD_P}

    #Railway remote configuration
#    url: jdbc:postgresql://altaria.proxy.rlwy.net:32649/railway
#    username: postgres
#    password: BkiIzqDwaYxQyVgGUOBSAxTihiBefvUV
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Bogota
  flyway:
    locations: classpath:migration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Security
jwt:
  secret: ${JWT_SECRET:change_this_to_a_strong_secret}
  expiration_minutes: ${JWT_EXP_MINUTES:180}

# Initial admin setup bootstrap (DataInitializer)
admin:
  setup:
    password: ${ADMIN_SETUP_PASSWORD:admin123}

# n8n local integration
#n8n:
#  api:
#    key: ${N8N_API_KEY:dev-secret-key-123}
#  webhook:
#    url: ${N8N_WEBHOOK_URL:https://masteracademy1492.app.n8n.cloud/webhook/confirmacion-cita}
#    reminder-url: ${N8N_WEBHOOK_REMINDER_URL:https://masteracademy1492.app.n8n.cloud/webhook/recordatorio-cita}

#n8n:
#  api:
#    key: ${N8N_API_KEY:dev-secret-key-123}
#  webhook:
#    url: ${N8N_WEBHOOK_URL:https://masteracademy1492.app.n8n.cloud/webhook-test/confirmacion-cita}
#    reminder-url: ${N8N_WEBHOOK_REMINDER_URL:https://masteracademy1492.app.n8n.cloud/webhook-test/recordatorio-cita}


# n8n remote integration
n8n:
  api:
    key: ${N8N_API_KEY:dev-secret-key-123}
  webhook:
    url: ${N8N_WEBHOOK_URL:http://20.186.24.153:5678/webhook/confirmacion-cita}
    reminder-url: ${N8N_WEBHOOK_REMINDER_URL:http://20.186.24.153:5678/webhook/recordatorio-cita}


# Evolution API configuration
evolution:
  api:
    url: ${EVOLUTION_API_URL:http://20.186.24.153:8080}
    key: ${EVOLUTION_API_KEY:Tu_api_key}
    instance: ${EVOLUTION_INSTANCE_NAME:Tu_instance_name}